services:
  - type: web
    name: movie-time-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: VITE_TOKEN
        sync: false
      - key: VITE_API_BASE_URL
        value: /api

  - type: web
    name: movie-time-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: FIREBASE_WEB_API_KEY
        sync: false
